export enum ErrorCode {
  // API Errors (1xxx)
  API_REQUEST_FAILED = 'API_REQUEST_FAILED',
  API_RESPONSE_INVALID = 'API_RESPONSE_INVALID',
  API_TIMEOUT = 'API_TIMEOUT',
  API_RATE_LIMIT = 'API_RATE_LIMIT',
  API_CONNECTION_ERROR = 'API_CONNECTION_ERROR',
  API_NOT_FOUND = 'API_NOT_FOUND',
  
  // Validation Errors (2xxx)
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  INVALID_COORDINATES = 'INVALID_COORDINATES',
  INVALID_STATE_CODE = 'INVALID_STATE_CODE',
  
  // System Errors (3xxx)
  SYSTEM_ERROR = 'SYSTEM_ERROR',
  SYSTEM_UNEXPECTED = 'SYSTEM_UNEXPECTED',
  CONFIGURATION_ERROR = 'CONFIGURATION_ERROR',
  
  // Business Logic Errors (4xxx)
  BUSINESS_LOGIC_ERROR = 'BUSINESS_LOGIC_ERROR',
  BUSINESS_OPERATION_FAILED = 'BUSINESS_OPERATION_FAILED',
}

export interface ErrorDetails {
  code: ErrorCode;
  message: string;
  statusCode?: number;
  originalError?: Error;
  metadata?: Record<string, unknown>;
}